source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'Wisper_Example' do
  pod "Wisper", :path => "../"
end

target 'Wisper_Tests' do
  pod "Wisper", :path => "../"
  pod "OCMock"
end
